apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lkexa9cuv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lkexa9cuv-nodejs 
  name: lkexa9cuv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lkexa9cuv-nodejs 
